/**
 * MedicalReport Model
 *
 * Stores the result of PDF report analysis. The binary PDF file itself is
 * NOT stored — only the extracted text and the AI-generated summary.
 *
 * DESIGN DECISIONS:
 *
 * 1. NO BINARY STORAGE:
 *    - Storing PDFs as Base64 or Buffer in MongoDB is an anti-pattern.
 *      It bloats the database, slows queries, and MongoDB documents have
 *      a 16MB hard limit.
 *    - In v1, the PDF is uploaded to the `uploads/` temp folder, extracted
 *      with pdf-parse, and the file is deleted immediately after.
 *    - IMPROVEMENT (v2): Move binary files to AWS S3. Store only the S3 key
 *      here (e.g. `s3Key: 'reports/userId/filename.pdf'`).
 *
 * 2. extractedText FIELD:
 *    - Stored for auditability. If the AI summary is poor, we can re-run
 *      analysis on the same text without asking the user to re-upload.
 *    - IMPROVEMENT: Add a `reAnalyze` endpoint that takes the stored
 *      extractedText and sends it to Gemini again.
 *
 * 3. keyFindings ARRAY:
 *    - Gemini will be prompted to return a structured list of key findings
 *      (abnormal values, doctor notes, diagnoses).
 *    - Stored as a String array for easy rendering as bullet points on the
 *      frontend without additional parsing.
 *
 * 4. pageCount:
 *    - pdf-parse returns this for free. Useful for UI display and for
 *      enforcing page limits in future (e.g., max 20 pages per upload).
 */

const mongoose = require('mongoose');

const MedicalReportSchema = new mongoose.Schema(
  {
    // ── Ownership ─────────────────────────────────────────────
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User ID is required'],
      index: true
    },

    // ── File Metadata ─────────────────────────────────────────
    originalFileName: {
      type: String,
      required: [true, 'Original file name is required'],
      trim: true,
      maxlength: [255, 'File name is too long']
    },


    storedFileName: {
    type: String,
    required: true,
    trim: true
},

filePath: {
    type: String,
    required: true,
    trim: true
},

mimeType: {
    type: String,
    required: true
},

    // File size in bytes (from Multer's file.size)
    fileSizeBytes: {
      type: Number,
      required: true,
      min: [1, 'File size must be greater than 0']
    },

    // Number of pages extracted by pdf-parse
    pageCount: {
      type: Number,
      default: null
    },

    // ── Extracted Content ─────────────────────────────────────
    // Raw text pulled from the PDF by pdf-parse
    extractedText: {
      type: String,
      required: [true, 'Extracted text is required'],
      // No maxlength here — medical reports can be long.
      // MongoDB's 16MB document limit is the practical ceiling.
    },

    // ── AI Analysis ───────────────────────────────────────────
    // The full narrative summary generated by Gemini
    aiSummary: {
      type: String,
      default: null
      // Null while analysis is in progress; populated after Gemini responds.
      // IMPROVEMENT: Add `analysisStatus: enum['pending', 'completed', 'failed']`
      // to support async/background processing in v2.
    },

    // Gemini-extracted list of key medical findings (abnormal values, diagnoses)
    keyFindings: {
      type: [String],
      default: []
    },

    // Follow-up actions Gemini recommends based on the report findings
    recommendations: {
      type: [String],
      default: []
    },

    // Urgency level parsed from Gemini's structured response
    urgencyLevel: {
      type: String,
      enum: {
        values: ['low', 'medium', 'high'],
        message: 'urgencyLevel must be low, medium, or high'
      },
      default: 'low'
    },

    // One-sentence explanation of the urgency level
    urgencyReason: {
      type: String,
      trim: true,
      default: ''
    },

    // The Gemini model version used for analysis (useful for reproducibility)
    modelUsed: {
      type: String,
      default: null
      // e.g. 'gemini-1.5-flash'
    }
  },
  {
    timestamps: true,
    toJSON: { versionKey: false }
  }
);

// ── Indexes ───────────────────────────────────────────────────
// Fetch all reports for a user, sorted newest first (most common query pattern)
MedicalReportSchema.index(
  { userId: 1, createdAt: -1 },
  { name: 'idx_report_user_date' }
);

module.exports = mongoose.model('MedicalReport', MedicalReportSchema);
